---
- name: "PLAYBOOK | Packer"
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "Install nmap"
      ansible.builtin.package:
        name: nmap
        state: present
  roles:
    - role: ansible-role-sysctl
