# role: jomrr.journald
# file: ansible/vars/journald.yml

# General options
journald_storage: "persistent"
journald_compress: "yes"
journald_seal: "yes"
journald_split_mode: "uid"
journald_sync_interval_sec: "5m"
journald_rate_limit_interval_sec: "30s"
journald_rate_limit_burst: "1000"
journald_system_max_use: "80%"
journald_system_keep_free: "10%"
journald_system_max_file_size: "1G"
journald_system_max_files: "100"
journald_runtime_max_use: "80%"
journald_runtime_keep_free: "10%"
journald_runtime_max_file_size: "1G"
journald_runtime_max_files: "10"
journald_max_retention_sec: ""
journald_max_file_sec: "1month"
journald_forward_to_syslog: "yes"
journald_forward_to_kmsg: "no"
journald_forward_to_console: "no"
journald_forward_to_wall: "yes"
journald_tty_path: "/dev/console"
journald_max_level_store: "debug"
journald_max_level_syslog: "debug"
journald_max_level_kmsg: "notice"
journald_max_level_console: "info"
journald_max_level_wall: "emerg"
journald_line_max: "48K"
journald_read_kmsg: "yes"
journald_audit: "yes"
