---
- name: "PLAYBOOK | Packer"
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "Import variable file for certificates"
      ansible.builtin.include_vars:
        file: vars/certificates.yml
    - name: "Import role certificates"
      ansible.builtin.include_role:
        name: certificates
    - name: "Import variable file for ubtu22cis"
      ansible.builtin.include_vars:
        file: vars/ubtu22cis.yml
      when: ansible_distribution_major_version == "22"
    - name: "Import role ubtu22cis"
      ansible.builtin.include_role:
        name: ubtu22cis
      when: ansible_distribution_major_version == "22"
